version: '3.8'
services:
  redis:
    image: redis:7.2-alpine
    ports:
      - 6379:6379
  clickhouse:
    image: clickhouse/clickhouse-server:23.8-alpine
    environment:
      CLICKHOUSE_DB: 'analytics'
    ports:
      - 8123:8123
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: 'analytics'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
