CREATE TABLE projects_views (
    id CHAR(36) PRIMARY KEY,
    projectId CHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    type ENUM('traffic', 'performance') NOT NULL,
    pg VARCHAR(255) NULL,
    ev VARCHAR(255) NOT NULL,
    dv VARCHAR(255) NULL,
    br VARCHAR(255) NULL,
    os VARCHAR(255) NULL,
    lc VARCHAR(255) NULL,
    ref VARCHAR(255) NULL,
    so VARCHAR(255) NULL,
    me VARCHAR(255) NULL,
    ca VARCHAR(255) NULL,
    cc VARCHAR(2) NULL,
    rg VARCHAR(255) NULL,
    ct VARCHAR(255) NULL,
    createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    FOREIGN KEY (projectId) REFERENCES projects(id) ON DELETE CASCADE  
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE projects_views_custom_events (
    id VARCHAR(36) PRIMARY KEY DEFAULT uuid_generate_v4(),
    viewId VARCHAR(255) NOT NULL,
    customEventName VARCHAR(255) NOT NULL,
    metaKey VARCHAR(255) NOT NULL,
    metaValue VARCHAR(255) NOT NULL,
    metaValueType ENUM('string', 'integer', 'float') NOT NULL DEFAULT 'string',
    createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    FOREIGN KEY (viewId) REFERENCES projects_views(id) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

