const sagaTypes = {
  LOAD_EXTENSIONS: 'UI_LOAD_EXTENSIONS',
  LOAD_PROJECTS: 'UI_LOAD_PROJECTS',
  LOAD_SHARED_PROJECTS: 'UI_LOAD_SHARED_PROJECTS',
  LOAD_PROJECT_ALERTS: 'UI_LOAD_PROJECT_ALERTS',
  LOGIN_ASYNC: 'LOGIN_ASYNC',
  SIGNUP_ASYNC: 'SIGNUP_ASYNC',
  EMAIL_VERIFY_ASYNC: 'EMAIL_VERIFY_ASYNC',
  UPDATE_USER_PROFILE_ASYNC: 'UPDATE_USER_PROFILE_ASYNC',
  DELETE_ACCOUNT_ASYNC: 'DELETE_ACCOUNT_ASYNC',
  LOGOUT: 'LOGOUT',
}

export default sagaTypes
