export const types = {
	// Synchronous
	FINISH_LOADING: 'FINISH_LOADING',
	LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
	EMAIL_VERIFY_SUCCESSFUL: 'EMAIL_VERIFY_SUCCESSFUL',
	EMAIL_VERIFY_FAILED: 'EMAIL_VERIFY_FAILED',
	SIGNUP_UP_SUCCESSFUL: 'SIGNUP_UP_SUCCESSFUL',
	UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
	LOGOUT: 'LOGOUT',
	SAVE_PATH: 'SAVE_PATH',
	DELETE_ACCOUNT_SUCCESS: 'DELETE_ACCOUNT_SUCCESS',

	// Asynchronous
	LOGIN_ASYNC: 'LOGIN_ASYNC',
	SIGNUP_ASYNC: 'SIGNUP_ASYNC',
	EMAIL_VERIFY_ASYNC: 'EMAIL_VERIFY_ASYNC',
	UPDATE_USER_PROFILE_ASYNC: 'UPDATE_USER_PROFILE_ASYNC',
	DELETE_ACCOUNT_ASYNC: 'DELETE_ACCOUNT_ASYNC'
}
