export enum LetterTemplate {
  SignUp = 'customer_sign-up',
  ConfirmPasswordChange = 'password-change_confirmation',
  PasswordChanged = 'password-change_information',
  MailAddressChangeConfirmation = 'mailaddress-change_confirmation',
  MailAddressHadChanged = 'mailaddress-change_information',
  PasswordChangeRequest = 'password-change_request',
  GDPRDataExport = 'gdpr_data_export',
  ProjectReport = 'project-report',
  TierWarning = 'tier-warning',
  ProjectInvitation = 'customer_project-invitation',
  TwoFAOn = '2fa-turned-on',
  TwoFAOff = '2fa-turned-off',
  TrialExpired = 'trial-expired',
  TrialEndsTomorrow = 'trial-ends-tomorrow',
  ProjectSubscriberInvitation = 'project-subscriber-invitation',
  ProjectTransfer = 'project-transfer',
  PayPalEmailUpdate = 'paypal-email-update',
  UsageOverLimit = 'usage-over-limit',
  DashboardLockedExceedingLimits = 'dashboard-locked-exceeding-limits',
  DashboardLockedPaymentFailure = 'dashboard-locked-payment-failure',
}
