export interface GlossaryItem {
  title: string
  slug: string
  category: string
  description: string
}

export const glossaryItems: GlossaryItem[] = [
  {
    title: 'A/B Testing',
    slug: 'a-b-testing',
    category: 'Experimentation',
    description:
      'A method for comparing two versions of a page, flow, or feature to see which one performs better against a defined goal.',
  },
  {
    title: 'Adblocker',
    slug: 'adblocker',
    category: 'Privacy',
    description:
      'Software that blocks ads, trackers, analytics scripts, and other third-party resources before they load in the browser.',
  },
  {
    title: 'Attribution Model',
    slug: 'attribution-model',
    category: 'Attribution',
    description:
      'The rule set an analytics platform uses to assign conversion credit across traffic sources, campaigns, and touchpoints.',
  },
  {
    title: 'Alerting',
    slug: 'alerting',
    category: 'Monitoring',
    description:
      'Automated notifications that warn teams about traffic spikes, drops, errors, uptime issues, or other analytics changes.',
  },
  {
    title: 'Assisted Conversion',
    slug: 'assisted-conversion',
    category: 'Attribution',
    description:
      'A conversion where a channel or touchpoint helped influence the final action but was not the last interaction before it.',
  },
  {
    title: 'Average Session Duration',
    slug: 'average-session-duration',
    category: 'Metrics',
    description:
      'The average time visitors spend on a website during one session, useful for judging engagement and content depth.',
  },
  {
    title: 'Bounce Rate',
    slug: 'bounce-rate',
    category: 'Metrics',
    description:
      'The percentage of sessions where a visitor leaves after viewing one page without triggering another meaningful interaction.',
  },
  {
    title: 'Bot Filtering',
    slug: 'bot-filtering',
    category: 'Data quality',
    description:
      'The process of detecting and excluding automated bot traffic so analytics reports better reflect real human visitors.',
  },
  {
    title: 'Bot Traffic',
    slug: 'bot-traffic',
    category: 'Data quality',
    description:
      'Visits and requests generated by automated crawlers, scrapers, monitors, malicious scripts, or other non-human clients.',
  },
  {
    title: 'Call to Action',
    slug: 'call-to-action',
    category: 'Conversion',
    description:
      'A prompt that asks a visitor to take the next step, such as signing up, booking a demo, downloading a guide, or buying.',
  },
  {
    title: 'CCPA',
    slug: 'ccpa',
    category: 'Privacy',
    description:
      'The California Consumer Privacy Act, a privacy law that gives California residents rights over how businesses use personal data.',
  },
  {
    title: 'Canonical URL',
    slug: 'canonical-url',
    category: 'SEO',
    description:
      'The preferred URL for a page when duplicate or similar versions exist, helping search engines consolidate ranking signals.',
  },
  {
    title: 'Click-through Rate',
    slug: 'click-through-rate',
    category: 'Metrics',
    description:
      'The percentage of people who click a link, ad, search result, email link, or button after seeing it.',
  },
  {
    title: 'Conversion',
    slug: 'conversion',
    category: 'Conversion',
    description:
      'A completed action that matters to a business, such as a signup, purchase, form submission, activation step, or download.',
  },
  {
    title: 'Conversion Rate',
    slug: 'conversion-rate',
    category: 'Conversion',
    description:
      'The percentage of visitors or sessions that complete a desired action during a selected reporting period.',
  },
  {
    title: 'Consent Management Platform',
    slug: 'consent-management-platform',
    category: 'Privacy',
    description:
      'Software that collects, stores, and applies visitor consent choices for cookies, analytics, ads, and other data processing.',
  },
  {
    title: 'Conversion Rate Optimization',
    slug: 'conversion-rate-optimization',
    category: 'Conversion',
    description:
      'The practice of improving pages, journeys, and offers so more visitors complete the actions that matter.',
  },
  {
    title: 'Cookie',
    slug: 'cookie',
    category: 'Privacy',
    description:
      'A small piece of browser-stored data that websites can use for preferences, sessions, measurement, or tracking.',
  },
  {
    title: 'Cookieless Tracking',
    slug: 'cookieless-tracking',
    category: 'Privacy',
    description:
      'Analytics measurement that does not store tracking cookies in the visitor browser while still reporting traffic and events.',
  },
  {
    title: 'Cookie Consent Banner',
    slug: 'cookie-consent-banner',
    category: 'Privacy',
    description:
      'A notice that asks visitors to accept, reject, or configure cookies and similar tracking technologies.',
  },
  {
    title: 'Cost per Click',
    slug: 'cost-per-click',
    category: 'Campaigns',
    description:
      'The amount an advertiser pays each time someone clicks an ad, often used to evaluate paid search and paid social efficiency.',
  },
  {
    title: 'Custom Event',
    slug: 'custom-event',
    category: 'Product analytics',
    description:
      'A named action tracked inside a website or app, such as clicking a pricing button, submitting a form, or creating a project.',
  },
  {
    title: 'Core Web Vitals',
    slug: 'core-web-vitals',
    category: 'Performance',
    description:
      'Google-defined user experience metrics that measure loading speed, interactivity, and visual stability on real pages.',
  },
  {
    title: 'Data Processing Agreement',
    slug: 'data-processing-agreement',
    category: 'Privacy',
    description:
      'A contract that defines how a processor handles personal data on behalf of a controller under privacy laws such as GDPR.',
  },
  {
    title: 'Data Residency',
    slug: 'data-residency',
    category: 'Privacy',
    description:
      'The physical or legal region where analytics data is stored and processed, often important for compliance and governance.',
  },
  {
    title: 'Data Retention',
    slug: 'data-retention',
    category: 'Privacy',
    description:
      'The policy that defines how long analytics, event, user, and operational data is kept before deletion or aggregation.',
  },
  {
    title: 'Dark Social',
    slug: 'dark-social',
    category: 'Attribution',
    description:
      'Traffic from private sharing channels such as messaging apps, email, documents, and communities that often appears as direct.',
  },
  {
    title: 'Direct Traffic',
    slug: 'direct-traffic',
    category: 'Attribution',
    description:
      'Traffic where the analytics platform cannot identify a referring website, campaign tag, search engine, or known source.',
  },
  {
    title: 'Engagement Rate',
    slug: 'engagement-rate',
    category: 'Metrics',
    description:
      'A percentage that shows how often visitors or users interact meaningfully with a page, product, or campaign.',
  },
  {
    title: 'Error Tracking',
    slug: 'error-tracking',
    category: 'Monitoring',
    description:
      'The practice of collecting and analyzing frontend or backend errors so teams can fix broken user experiences faster.',
  },
  {
    title: 'Event Tracking',
    slug: 'event-tracking',
    category: 'Product analytics',
    description:
      'The practice of recording user actions such as clicks, submissions, purchases, downloads, and product interactions.',
  },
  {
    title: 'Experiment',
    slug: 'experiment',
    category: 'Experimentation',
    description:
      'A controlled test that exposes visitors or users to variants and measures which version performs better against a goal.',
  },
  {
    title: 'Exit Rate',
    slug: 'exit-rate',
    category: 'Metrics',
    description:
      'The percentage of page views where a page was the final page in a session before the visitor left the website.',
  },
  {
    title: 'Feature Flag',
    slug: 'feature-flag',
    category: 'Product analytics',
    description:
      'A switch that lets teams enable, disable, target, or gradually roll out product features without deploying new code.',
  },
  {
    title: 'First-party Data',
    slug: 'first-party-data',
    category: 'Privacy',
    description:
      'Data collected directly from your own audience, website, product, or customers rather than purchased from external brokers.',
  },
  {
    title: 'First Party Cookie',
    slug: 'first-party-cookie',
    category: 'Privacy',
    description:
      'A cookie set by the website domain a visitor is currently using, usually for sessions, preferences, or same-site analytics.',
  },
  {
    title: 'Funnel',
    slug: 'funnel',
    category: 'Conversion',
    description:
      'A sequence of steps visitors move through before reaching a goal, such as landing page, signup, checkout, and payment.',
  },
  {
    title: 'Funnel Drop-off',
    slug: 'funnel-drop-off',
    category: 'Conversion',
    description:
      'The point in a funnel where visitors leave before completing the next step or reaching the final conversion.',
  },
  {
    title: 'GDPR',
    slug: 'gdpr',
    category: 'Privacy',
    description:
      'The European Union privacy regulation that governs how organizations collect, process, store, and protect personal data.',
  },
  {
    title: 'Goal Tracking',
    slug: 'goal-tracking',
    category: 'Conversion',
    description:
      'The setup and measurement of important website or product outcomes such as signups, purchases, leads, and activations.',
  },
  {
    title: 'Google Analytics 4',
    slug: 'google-analytics-4',
    category: 'Analytics platforms',
    description:
      "Google Analytics 4, often called GA4, is Google's event-based analytics platform for websites and apps.",
  },
  {
    title: 'Indexability',
    slug: 'indexability',
    category: 'SEO',
    description:
      'A page status that determines whether search engines are allowed and able to include the page in search results.',
  },
  {
    title: 'IP Address',
    slug: 'ip-address',
    category: 'Technology',
    description:
      'A network address assigned to a device or connection, often used for routing, approximate geolocation, security, and abuse prevention.',
  },
  {
    title: 'JavaScript Error',
    slug: 'javascript-error',
    category: 'Monitoring',
    description:
      'A browser-side runtime error that can break user interactions, tracking, forms, checkout flows, or product features.',
  },
  {
    title: 'Landing Page',
    slug: 'landing-page',
    category: 'Conversion',
    description:
      'The page a visitor lands on after clicking a search result, ad, campaign link, referral link, or social post.',
  },
  {
    title: 'Last-click Attribution',
    slug: 'last-click-attribution',
    category: 'Attribution',
    description:
      'An attribution model that gives full conversion credit to the final known source or touchpoint before conversion.',
  },
  {
    title: 'Live Visitors',
    slug: 'live-visitors',
    category: 'Real-time analytics',
    description:
      'The visitors currently active on a website, usually shown in real time with their pages, sources, and locations.',
  },
  {
    title: 'Customer Acquisition Cost',
    slug: 'customer-acquisition-cost',
    category: 'Campaigns',
    description:
      'The average cost to acquire a new customer, calculated from sales and marketing spend over a defined period.',
  },
  {
    title: 'Customer Lifetime Value',
    slug: 'customer-lifetime-value',
    category: 'Campaigns',
    description:
      'The estimated total revenue or gross profit a customer generates over their relationship with a business.',
  },
  {
    title: 'Meta Description',
    slug: 'meta-description',
    category: 'SEO',
    description:
      'An HTML summary of a page that can appear in search results and influence search click-through rate.',
  },
  {
    title: 'Multi-touch Attribution',
    slug: 'multi-touch-attribution',
    category: 'Attribution',
    description:
      'Attribution that distributes conversion credit across multiple channels or touchpoints in a customer journey.',
  },
  {
    title: 'Organic Search',
    slug: 'organic-search',
    category: 'Acquisition',
    description:
      'Unpaid traffic from search engines, typically driven by ranking pages, technical SEO, content quality, and search intent.',
  },
  {
    title: 'Page Title',
    slug: 'page-title',
    category: 'SEO',
    description:
      'The HTML title of a page, used by browsers and search engines to describe the page topic in tabs and results.',
  },
  {
    title: 'Page Speed',
    slug: 'page-speed',
    category: 'Performance',
    description:
      'How quickly a page loads and becomes usable, including server response, asset loading, rendering, and Core Web Vitals.',
  },
  {
    title: 'Page View',
    slug: 'page-view',
    category: 'Metrics',
    description:
      'A tracked instance of a page being loaded or viewed, often counted every time a visitor opens or navigates to a page.',
  },
  {
    title: 'Personal Data',
    slug: 'personal-data',
    category: 'Privacy',
    description:
      'Information that can identify a person directly or indirectly, such as an email address, user ID, precise location, or IP address.',
  },
  {
    title: 'Public Dashboard',
    slug: 'public-dashboard',
    category: 'Reporting',
    description:
      'A shareable analytics dashboard that lets people view selected metrics without needing full account access.',
  },
  {
    title: 'Real User Monitoring',
    slug: 'real-user-monitoring',
    category: 'Performance',
    description:
      'Performance monitoring based on real visitor devices, browsers, networks, and pages rather than lab tests alone.',
  },
  {
    title: 'Referral Traffic',
    slug: 'referral-traffic',
    category: 'Attribution',
    description:
      'Visitors who arrive after clicking a link from another website, excluding common search engines and tagged campaigns.',
  },
  {
    title: 'Referrer',
    slug: 'referrer',
    category: 'Attribution',
    description:
      'The source URL or origin the browser reports when a visitor clicks from one page to another.',
  },
  {
    title: 'Return on Investment',
    slug: 'return-on-investment',
    category: 'Campaigns',
    description:
      'A profitability metric that compares the value generated by a campaign, channel, or project against its cost.',
  },
  {
    title: 'Revenue Analytics',
    slug: 'revenue-analytics',
    category: 'Revenue',
    description:
      'Analytics that connects traffic, campaigns, users, events, and conversions to revenue and payment data.',
  },
  {
    title: 'Revenue Attribution',
    slug: 'revenue-attribution',
    category: 'Attribution',
    description:
      'The process of connecting revenue back to the channels, campaigns, pages, and touchpoints that influenced it.',
  },
  {
    title: 'Robots.txt',
    slug: 'robots-txt',
    category: 'SEO',
    description:
      'A text file that tells search engine crawlers which parts of a website they are allowed or disallowed to crawl.',
  },
  {
    title: 'Search Analytics',
    slug: 'search-analytics',
    category: 'SEO',
    description:
      'The analysis of search queries, impressions, clicks, rankings, pages, and search visibility over time.',
  },
  {
    title: 'Search Query',
    slug: 'search-query',
    category: 'SEO',
    description:
      'The word or phrase a person enters into a search engine before seeing or clicking a search result.',
  },
  {
    title: 'SERP',
    slug: 'serp',
    category: 'SEO',
    description:
      'The search engine results page shown after a query, including organic results, ads, snippets, and other features.',
  },
  {
    title: 'Server-side Tracking',
    slug: 'server-side-tracking',
    category: 'Technology',
    description:
      'Analytics collection performed from a server rather than only from browser JavaScript, often used for reliability and control.',
  },
  {
    title: 'Search Engine Optimization',
    slug: 'search-engine-optimization',
    category: 'SEO',
    description:
      'The practice of improving a website so search engines can discover, understand, and rank its pages for relevant queries.',
  },
  {
    title: 'Segmentation',
    slug: 'segmentation',
    category: 'Analysis',
    description:
      'The practice of splitting analytics data into groups by source, country, device, browser, campaign, behavior, or user property.',
  },
  {
    title: 'Session',
    slug: 'session',
    category: 'Metrics',
    description:
      'A group of interactions from one visitor within a defined time window, usually ending after inactivity or a new campaign source.',
  },
  {
    title: 'Session Replay',
    slug: 'session-replay',
    category: 'Product analytics',
    description:
      'A recorded reconstruction of a visitor session that helps teams debug journeys, friction, errors, and UX issues.',
  },
  {
    title: 'Sitemap',
    slug: 'sitemap',
    category: 'SEO',
    description:
      'A file or page that lists important URLs so search engines and users can discover website content more easily.',
  },
  {
    title: 'Scroll Depth',
    slug: 'scroll-depth',
    category: 'Metrics',
    description:
      'A measurement of how far visitors scroll down a page, often used to evaluate content engagement.',
  },
  {
    title: 'Third Party Cookie',
    slug: 'third-party-cookie',
    category: 'Privacy',
    description:
      'A cookie set by a domain other than the website a visitor is viewing, commonly used for cross-site advertising and tracking.',
  },
  {
    title: 'Time on Page',
    slug: 'time-on-page',
    category: 'Metrics',
    description:
      'The estimated amount of time a visitor spends on a page before navigating away, closing the tab, or becoming inactive.',
  },
  {
    title: 'Traffic Channel',
    slug: 'traffic-channel',
    category: 'Attribution',
    description:
      'A grouped source of website visits, such as organic search, referral, direct, paid search, email, social, or display.',
  },
  {
    title: 'Traffic Spike',
    slug: 'traffic-spike',
    category: 'Monitoring',
    description:
      'A sudden increase in website visits, events, errors, or conversions compared with the normal baseline.',
  },
  {
    title: 'UTM Code',
    slug: 'utm-code',
    category: 'Campaigns',
    description:
      'A campaign tracking parameter added to URLs so analytics tools can identify source, medium, campaign, term, and content.',
  },
  {
    title: 'Unique Visitor',
    slug: 'unique-visitor',
    category: 'Metrics',
    description:
      'An estimate of one distinct visitor during a reporting period, counted once even if they view multiple pages.',
  },
  {
    title: 'Uptime Monitoring',
    slug: 'uptime-monitoring',
    category: 'Monitoring',
    description:
      'Automated checks that verify whether a website, endpoint, or service is reachable and responding as expected.',
  },
  {
    title: 'User Agent',
    slug: 'user-agent',
    category: 'Technology',
    description:
      'A browser-provided string that identifies the client application, operating system, device type, and browser version.',
  },
  {
    title: 'User Profile',
    slug: 'user-profile',
    category: 'Product analytics',
    description:
      'A view of known user or visitor activity that groups sessions, events, attributes, and journey history.',
  },
  {
    title: 'Web Analytics',
    slug: 'web-analytics',
    category: 'Analytics fundamentals',
    description:
      'The collection and analysis of website traffic, visitor behavior, conversion, performance, and acquisition data.',
  },
  {
    title: 'Website Monitoring',
    slug: 'website-monitoring',
    category: 'Monitoring',
    description:
      'The ongoing measurement of website availability, performance, errors, and traffic health so issues are caught quickly.',
  },
]
