export const types = {
  // Authorisation
  LOGIN_FAILED: 'LOGIN_FAILED',
  SIGN_UP_FAILED: 'SIGN_UP_FAILED',
  UPDATE_USER_PROFILE_FAILED: 'UPDATE_USER_PROFILE_FAILED',
  CREATE_NEW_PASSWORD_FAILED: 'CREATE_NEW_PASSWORD_FAILED',
  DELETE_ACCOUNT_FAILED: 'DELETE_ACCOUNT_FAILED',

  // Projects
  CREATE_NEW_PROJECT_FAILED: 'CREATE_NEW_PROJECT_FAILED',
  UPDATE_PROJECT_FAILED: 'UPDATE_PROJECT_FAILED',
  DELETE_PROJECT_FAILED: 'DELETE_PROJECT_FAILED',

  // Common
  CLEAR_ERRORS: 'CLEAR_ERRORS',
}
