export const types = {
	// Authorisation
	LOGIN_FAILED: 'LOGIN_FAILED',
	SIGN_UP_FAILED: 'SIGN_UP_FAILED',
	UPDATE_USER_PROFILE_FAILED: 'UPDATE_USER_PROFILE_FAILED',
	CREATE_NEW_PASSWORD_FAILED: 'CREATE_NEW_PASSWORD_FAILED',
	DELETE_ACCOUNT_FAILED: 'DELETE_ACCOUNT_FAILED',

	// Common
	CLEAR_ERRORS: 'CLEAR_ERRORS'
}
