const routes = Object.freeze({
  signin: '/login',
  signup: '/signup',
  performance: '/performance',
  errorTracking: '/error-tracking',
  captchaLanding: '/captcha',
  captchaDemo: '/captcha/demo',
  onboarding: '/onboarding',
  reset_password: '/recovery',
  new_password_form: '/password-reset/:id',
  confirm_share: '/share/:id',
  confirm_subcription: '/projects/:id/subscribers/invite',
  main: '/',
  dashboard: '/dashboard',
  user_settings: '/user-settings',
  verify: '/verify/:id',
  change_email: '/change-email/:id',
  project_settings: '/projects/settings/:id',
  project: '/projects/:id',
  billing: '/billing',
  privacy: '/privacy',
  cookiePolicy: '/cookie-policy',
  terms: '/terms',
  contact: '/contact',
  transfer_confirm: '/project/transfer/confirm',
  transfer_reject: '/project/transfer/cancel',
  socialised: '/socialised',
  gsc_connected: '/gsc-connected',
  open: '/open',
  ref: '/ref/:id',
  blog: '/blog',
  imprint: '/imprint',
  forMarketers: '/for-marketers',
  forStartups: '/for-startups',
  forSmallBusinesses: '/for-small-businesses',
  organisations: '/organisations',
  organisation: '/organisations/:id',
  dataPolicy: '/data-policy',

  // Free tools
  tools: '/tools',
  utm_generator: '/tools/utm-generator',
  roi_calculator: '/tools/roi-calculator',
  ctr_calculator: '/tools/ctr-calculator',
})

export default routes
