export const types = {
  // Synchronous
  FINISH_LOADING: 'FINISH_LOADING',
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  EMAIL_VERIFY_SUCCESSFUL: 'EMAIL_VERIFY_SUCCESSFUL',
  EMAIL_VERIFY_FAILED: 'EMAIL_VERIFY_FAILED',
  SIGNUP_UP_SUCCESSFUL: 'SIGNUP_UP_SUCCESSFUL',
  UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
  LOGOUT: 'LOGOUT',
  SAVE_PATH: 'SAVE_PATH',
  DELETE_ACCOUNT_SUCCESS: 'DELETE_ACCOUNT_SUCCESS',
  DELETE_SHARE_PROJECT: 'DELETE_SHARE_PROJECT',
  SET_USER_SHARE_DATA: 'SET_USER_SHARE_DATA',
  SET_DONT_REMEMBER: 'SET_DONT_REMEMBER',
  UPDATE_USER_DATA: 'UPDATE_USER_DATA',
  SET_API_KEY: 'SET_API_KEY',
  SET_USER: 'SET_USER',

  // Asynchronous
  LOGIN_ASYNC: 'LOGIN_ASYNC',
  SIGNUP_ASYNC: 'SIGNUP_ASYNC',
  EMAIL_VERIFY_ASYNC: 'EMAIL_VERIFY_ASYNC',
  UPDATE_USER_PROFILE_ASYNC: 'UPDATE_USER_PROFILE_ASYNC',
  DELETE_ACCOUNT_ASYNC: 'DELETE_ACCOUNT_ASYNC',
}
