export const types = {
  // Sync
  LOAD_PROJECTS: 'LOAD_PROJECTS',
  SET_PROJECTS_ERROR: 'SET_PROJECTS_ERROR',
  SET_PROJECTS_LOADING: 'SET_PROJECTS_LOADING',
  REMOVE_PROJECT: 'REMOVE_PROJECT',

  // Async
  SET_PROJECTS: 'SET_PROJECTS',
}
