export const types = {
  LOAD_PROJECTS: 'LOAD_PROJECTS',
  SET_PROJECTS_ERROR: 'SET_PROJECTS_ERROR',
  SET_PROJECTS_LOADING: 'SET_PROJECTS_LOADING',
  REMOVE_PROJECT: 'REMOVE_PROJECT',
  SET_PROJECT_CACHE: 'SET_PROJECT_CACHE',
  DELETE_PROJECT_CACHE: 'DELETE_PROJECT_CACHE',
  SET_PROJECT_VIEW_PREFS: 'SET_PROJECT_VIEW_PREFS',
  SET_PROJECTS: 'SET_PROJECTS',
  SET_PROJECT: 'SET_PROJECT',
}
