export const types = {
  ACCOUNT_DELETED: 'ALERT_ACCOUNT_DELETED',
  ACCOUNT_UPDATED: 'ALERT_ACCOUNT_UPDATED',
  NEW_PASSWORD: 'ALERT_NEW_PASSWORD',

  // Projects
  CREATE_NEW_PROJECT_SUCCESS: 'ALERT_CREATE_NEW_PROJECT_SUCCESS',
  DELETE_PROJECT_SUCCESS: 'ALERT_DELETE_PROJECT_SUCCESS',
  ROLE_UPDATED: 'ALERT_ROLE_UPDATED',
  INVITE_USER: 'ALERT_INVITE_USER',
  REMOVE_USER: 'ALERT_REMOVE_USER',
  USER_SHARED_UPDATE: 'ALERT_USER_SHARED_UPDATE',

  // Common
  CLEAR_ALERTS: 'CLEAR_ALERTS',
}
