export const types = {
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  ACCOUNT_UPDATED: 'ACCOUNT_UPDATED',
  NEW_PASSWORD: 'NEW_PASSWORD',

  // Projects
  CREATE_NEW_PROJECT_SUCCESS: 'CREATE_NEW_PROJECT_SUCCESS',
  DELETE_PROJECT_SUCCESS: 'DELETE_PROJECT_SUCCESS',

  // Common
  CLEAR_ALERTS: 'CLEAR_ALERTS'
}
