export enum LetterTemplate {
  SignUp = 'customer_sign-up',
  ConfirmPasswordChange = 'password-change_confirmation',
  PasswordChanged = 'password-change_information',
  MailAddressChangeConfirmation = 'mailaddress-change_confirmation',
  MailAddressHadChanged = 'mailaddress-change_information',
  ProjectReport = 'project-report',
  TierWarning = 'tier-warning',
  SubscriptionCancelled = 'subscription-cancelled',
  ProjectInvitation = 'customer_project-invitation',
  TwoFAOn = '2fa-turned-on',
  TwoFAOff = '2fa-turned-off',
  TrialExpired = 'trial-expired',
  TrialEndsTomorrow = 'trial-ends-tomorrow',
  ProjectSubscriberInvitation = 'project-subscriber-invitation',
  ProjectTransfer = 'project-transfer',
  UsageOverLimit = 'usage-over-limit',
  DashboardLockedExceedingLimits = 'dashboard-locked-exceeding-limits',
  DashboardLockedPaymentFailure = 'dashboard-locked-payment-failure',
  OrganisationInvitation = 'organisation-invitation',
  SocialIdentityLinked = 'social-identity-linked',
  NoEventsAfterSignup = 'no-events-after-signup',
}
